# Generated by Django 3.2 on 2023-06-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recruiting',
            new_name='Recruiting_list',
        ),
    ]
