# Generated by Django 3.2 on 2023-06-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0002_rename_recruiting_recruiting_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiting_list',
            name='company_name',
            field=models.CharField(db_column='company_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='recruiting_list',
            name='job',
            field=models.CharField(db_column='job', max_length=100),
        ),
    ]
