# Generated by Django 3.2 on 2023-06-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiting', '0003_auto_20230626_2015'),
        ('recruiting', '0003_auto_20230626_2048'),
    ]

    operations = [
    ]
