# Generated by Django 3.2 on 2023-06-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_png', models.CharField(max_length=100)),
                ('com_rank', models.CharField(max_length=7)),
                ('com_name', models.CharField(max_length=100)),
                ('com_in', models.TextField()),
            ],
        ),
    ]
