# Generated by Django 3.2 on 2023-06-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_list',
            name='com_png',
            field=models.CharField(max_length=100),
        ),
    ]
