# Generated by Django 3.2 on 2023-06-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company_list',
        ),
    ]
