# Generated by Django 3.2 on 2023-06-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0003_company_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company_list',
        ),
    ]
