# Generated by Django 3.2 on 2023-06-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_info', '0004_delete_company_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_png', models.CharField(max_length=100)),
                ('com_rank', models.CharField(max_length=7)),
                ('com_name', models.CharField(max_length=100)),
                ('com_in', models.TextField()),
                ('industry_field', models.CharField(max_length=100)),
                ('workforce', models.CharField(max_length=40)),
                ('com_detail_type', models.CharField(max_length=30)),
                ('est_date', models.CharField(max_length=50)),
                ('capital', models.CharField(max_length=50)),
                ('sales', models.CharField(max_length=50)),
                ('ceo', models.CharField(max_length=30)),
                ('initial_salary', models.CharField(max_length=30)),
                ('main_business', models.CharField(max_length=200)),
                ('insurance', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=60)),
                ('com_detail_address', models.CharField(max_length=170)),
                ('subsidiary', models.CharField(max_length=270)),
            ],
        ),
    ]
