# Generated by Django 3.2 on 2023-06-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0005_company_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ml_final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
